### ISSUE TITLE
Adding Few Descriptive Enhancement in Landing Page

### ISSUE THREAD

**Issue by kinderasteroid** [kinderneutron/kinderneutron-web-app#8]
**Feature request Title.**
----------------------------------------
Adding Few Descriptive Enhancement in Landing Page

**Describe:**
----------------------------------------
 I liked the Design. I appriciate the Usage of Saas Design.But can we Apply Some Modifications? Something like the Picture Attached Below, Let one Section show Video and Other Section Show the Status of Light/Circuit attached and One Timely Dynamic Graph May be To show Electicity usage in volts or Status when Light was On (Optional) IF posstible make a design?

**Implementation Idea(If any)**
-----------------------------------------
Modification in the Landing Page Code and Reffering Other Design Integration Ideas . Also Asking ChatGPT for Solutions 

**Additional context**
-----------------------------------------
_Attached Image_

![Porto-Admin](https://github.com/kinderneutron/kinderneutron-web-app/assets/84179566/6dcf2fb1-ded2-4025-ba7a-0d7da3d26d7d)

**Comment by VLBHAT31** [comment]
@kinderasteroid design updated. And is sent for review.
